#!/usr/bin/python
import time
import webbrowser
option='''press 1:ente words for search'
'''
print option
ch_raw_input()

if (ch==1):
	search_data=raw_input('enter data')
	final_data=search_data.strip()
	done_data=fnal_data.spiit()
	print done_data
	for i in  done_data:
	  webbrowser.open_new_tab('https://www.google.com/search?q='+i)
 
